api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    formats:
        json: ['application/json', 'application/ld+json']
    patch_formats:
        json: ['application/merge-patch+json']

    # OpenApi (Swagger).
    enable_swagger: true
    enable_swagger_ui: true
    swagger:
        versions: [ 3 ]
        api_keys:
            apiKey:
                name: Authorization
                type: header

    show_webby: false
    graphql:
        # Enabled by default with installed webonyx/graphql-php.
        enabled: false
