# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    trusted_proxies: '%env(TRUSTED_PROXIES)%'

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    router:
        default_uri: '%env(string:DEFAULT_URI)%'

    #esi: true
    #fragments: true

    http_client:
        scoped_clients:
            economics.client:
                base_uri: '%env(APP_ECONOMICS_URI)%'
                scope: '%env(APP_ECONOMICS_URI)%'
                headers:
                    x-api-key: '%env(APP_ECONOMICS_API_KEY)%'
            leantime.client:
                base_uri: '%env(APP_LEANTIME_URI)%'
                scope: '%env(APP_LEANTIME_URI)%'
                headers:
                    Content-Type: 'application/json'
                    x-api-key: '%env(APP_LEANTIME_API_KEY)%'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
