framework:
    messenger:
        # Send failed messages to this transport for later handling.
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            sync: 'sync://'
            async:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                retry_strategy:
                    # 1, 3, 9, 27
                    max_retries: 4
                    delay: 60000 # 1 minutes
                    multiplier: 3
                    max_delay: 3600000 # 1 hour
            # @see https://symfony.com/doc/current/messenger.html#saving-retrying-failed-messages
            failed:
                dsn: '%env(MESSENGER_TRANSPORT_DSN_FAILED)%'
                options:
                    auto_setup: 'false'

        routing:
            # DetectionResults needs to handled synchronously to be
            # able to access the security context
            App\Entity\DetectionResult: sync

            App\Message\PersistDetectionResult: async
            App\Message\ProcessDetectionResult: async

when@test:
    framework:
        messenger:
            transports:
                async: 'in-memory://'