services:
  rabbit:
    image: rabbitmq:4-management-alpine
    restart: unless-stopped
    networks:
      - app
      - frontend
    environment:
      - "RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}"
      - "RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}"
      - "RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}"
    volumes:
      - ".docker/data/rabbitmq:/var/lib/rabbitmq/mnesia/"

  supervisor:
    image: itkdev/supervisor-php8.4:alpine
    restart: unless-stopped
    stop_grace_period: 20s
    environment:
      - APP_SUPERVISOR_COMMAND=/app/bin/console messenger:consume --env=prod --no-debug --time-limit=900 --failure-limit=1 async
      - APP_SUPERVISOR_WORKERS=1
      - APP_SUPERVISOR_USER=deploy
      - PHP_MEMORY_LIMIT=256M
    networks:
      - app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
      - ../../shared/.env.local:/app/.env.local
    depends_on:
      - rabbit

  phpfpm:
    volumes:
      - ../../shared/.env.local:/app/.env.local
    depends_on:
      - rabbit
