services:
  rabbit:
    image: rabbitmq:4-management-alpine
    networks:
      - app
      - frontend
    environment:
      - "RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}"
      - "RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}"
      - "RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}"
    volumes:
      - ".docker/data/rabbitmq:/var/lib/rabbitmq/mnesia/"

  supervisor:
    stop_grace_period: 20s
    environment:
      - APP_SUPERVISOR_COMMAND=/app/bin/console messenger:consume --env=prod --no-debug --time-limit=900 --failure-limit=1 async
      - APP_SUPERVISOR_WORKERS=1
      - APP_SUPERVISOR_USER=deploy
